# Generated by Django 3.2.4 on 2021-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_no', models.IntegerField()),
                ('banner_heading', models.CharField(max_length=200)),
                ('banner_content', models.TextField(max_length=500)),
            ],
        ),
    ]
