# Generated by Django 3.2.4 on 2021-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_content',
            field=models.TextField(),
        ),
    ]
