# Generated by Django 3.2.4 on 2021-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rework'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teamimg')),
                ('memb_name', models.CharField(max_length=50)),
                ('memb_job', models.CharField(max_length=50)),
            ],
        ),
    ]
