# Generated by Django 3.2.4 on 2021-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('plan_price', models.CharField(max_length=50000)),
                ('plan_user', models.CharField(max_length=100)),
                ('plan_space', models.CharField(max_length=100)),
                ('plan_source', models.CharField(max_length=100)),
                ('plan_support', models.CharField(max_length=50)),
                ('customization', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
