# Generated by Django 3.2.4 on 2021-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='customization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
