# Generated by Django 3.2.4 on 2021-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pricing_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='is_main',
            field=models.BooleanField(null=True),
        ),
    ]
