# Generated by Django 3.2.4 on 2021-06-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pricing_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workimg')),
                ('work_text', models.CharField(max_length=100)),
            ],
        ),
    ]
