# Generated by Django 3.2.4 on 2021-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='working_text',
            field=models.CharField(default='lorem ispsun manjo man', max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_text',
            field=models.CharField(max_length=50),
        ),
    ]
