# Generated by Django 3.2.4 on 2021-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210603_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='transwork')),
                ('image_large', models.ImageField(upload_to='transwork')),
            ],
        ),
    ]
